Create car_detection_image.py
powerexploit/Awesome-Python-Scripts pull request #110
Opened 2020-08-16 08:33 UTC by ryuk156

issue :  https://github.com/ankitdobhal/Awesome-Python-Scripts/issues/93

About Pull request : 
This pr consist of car detection in an image if a car is detected in an image the green rectangle will be drawn , it uses pre trained car classifer

Demo : 
![image](https://user-images.githubusercontent.com/49101492/90330234-cd5b7e00-dfc8-11ea-9088-9a9c9a59db4a.png)

2020-08-16 08:38 UTC, ryuk156 commented
@ankitdobhal review and merge

2020-08-16 10:33 UTC, disha2sinha requested changes
Don't put so many new lines between codes

2020-08-16 10:33 UTC, disha2sinha commented on Image-Processing/car_detection_image.py
> +
Remove new line

2020-08-16 10:33 UTC, disha2sinha commented on Image-Processing/car_detection_image.py
> +
remove excess new line

2020-08-16 10:33 UTC, disha2sinha commented on Image-Processing/car_detection_image.py
> +
remove excess new lines

2020-08-16 10:33 UTC, disha2sinha commented on Image-Processing/car_detection_image.py
> +
remove new line at the end

2020-08-16 10:49 UTC, ryuk156 commented
@disha2sinha done review please

2020-08-17 14:00 UTC, disha2sinha requested changes
Put space around operators and after comma

2020-08-17 14:00 UTC, disha2sinha commented on Image-Processing/car_detection_image.py
> +cars=car_tracker.detectMultiScale(black_and_white) #detect cars
Put a new line before starting for loop

2020-08-17 14:00 UTC, disha2sinha commented on Image-Processing/car_detection_image.py
> +    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3) ##this loop will create grren rectangle when car is detected
put new line after starting for loop

2020-08-17 17:58 UTC, ryuk156 commented
@disha2sinha done

2020-08-18 14:16 UTC, disha2sinha commented
Add README (guide) along with this inside the folder same as your
Update the README with appropriate installation methods and description guidelines.
Maintain proper Contribution protocols protocols (ignore if you're already following it!) & good practices!

2020-08-19 16:52 UTC, closed without merging