Convert Numbers/Digits to their respective English representation.
powerexploit/Awesome-Python-Scripts pull request #115
Opened 2020-08-16 11:12 UTC by abhip99

I have wrote the script to do this..

2020-08-16 11:33 UTC, SKAUL05 requested changes
Follow [PEP8 Guidelines](https://www.python.org/dev/peps/pep-0008/) while coding.

2020-08-16 11:33 UTC, SKAUL05 commented on Basic-Scripts/int_to_en.py
> +    d = { 0 : 'zero', 1 : 'one', 2 : 'two', 3 : 'three', 4 : 'four', 5 : 'five',
Include Docstrings in your function definition.

2020-08-16 11:33 UTC, SKAUL05 commented on Basic-Scripts/int_to_en.py
> +    m = k * 1000
Use meaningful variable names.

2020-08-16 11:33 UTC, SKAUL05 commented on Basic-Scripts/int_to_en.py
> +number = int(input())
Include the input part in `main` function. Ask User for Input.

2020-08-16 13:15 UTC, abhip99 commented
I have resolved the issue mention by @SKAUL05  , Can you review again my request to merge the code into main branch.

2020-08-16 15:54 UTC, SKAUL05 requested changes

2020-08-16 15:54 UTC, SKAUL05 commented on Basic-Scripts/int_to_en.py
> +    number = int(input())
Ask the user for input
` number = int(input("Enter Number"))`

2020-08-16 16:18 UTC, abhip99 commented
Requested change has been made.

2020-08-16 16:22 UTC, SKAUL05 commented
> Requested change has been made.

@abhip99 Rebase your PR, it already contains 4 commits.

2020-08-24 09:11 UTC, SKAUL05 approved these changes
Good to go @abhip99 
Review & Merge @ankitdobhal

2020-08-27 15:47 UTC, merged