Script to download Medium articles
powerexploit/Awesome-Python-Scripts pull request #118
Opened 2020-08-16 12:05 UTC by Namyalg

This script written in Python uses BeautifulSoup library. It can be used to download Medium Articles given the URL

2020-08-16 14:04 UTC, Neilblaze commented
Thank you for your contribution @Namyalg  !

Before I approve changes to the PR, I will request you the following changes mentioned below.

- Add README (guide) along with this inside the folder same as your `<filename>`
- Shift most of the comments as instructions in the README file.
- Maintain proper [Contribution protocols](https://github.com/ankitdobhal/Awesome-Python-Scripts/blob/master/Contribution.md) (ignore if you're already following it!) & [good practices](https://gist.github.com/sloria/7001839)!
- Recheck if there are any intendation errors in the script.

Rest LGTM :+1:

2020-08-16 14:13 UTC, Namyalg commented
Yep, will do so!

On Sun, Aug 16, 2020, 7:34 PM Pratyay Banerjee <notifications@github.com>
wrote:

> Thank you for your contribution @Namyalg <https://github.com/Namyalg> !
>
> Before I approve changes to the PR, I will request you the following
> changes mentioned below.
>
>    - Add README (guide) along with this inside the folder same as your
>    <filename>
>    - Shift most of the comments as instructions in the README file.
>    - Maintain proper Contribution protocols
>    <https://github.com/ankitdobhal/Awesome-Python-Scripts/blob/master/Contribution.md>
>    (ignore if you're already following it!) & good practices
>    <https://gist.github.com/sloria/7001839>!
>    - Recheck if there are any intendation errors in the script.
>
> Rest LGTM 👍
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ankitdobhal/Awesome-Python-Scripts/pull/118#issuecomment-674530533>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM3BEYKWIQR77DUDCXVQCS3SA7RPJANCNFSM4QAZMETA>
> .
>

2020-08-17 07:30 UTC, Neilblaze commented
@Namyalg it'll better if you remove those .png files from the PR folder!

2020-08-17 07:31 UTC, Neilblaze commented on Web-Scraping/Medium_article_downloader/README.md
> +![Image](promptURL.PNG)
Delete this image!

2020-08-17 07:32 UTC, Neilblaze requested changes

2020-08-17 07:32 UTC, Neilblaze commented on Web-Scraping/Medium_article_downloader/README.md
> +![Image](content.PNG)
& this too!

2020-08-17 07:33 UTC, Neilblaze commented
It is highly recommended if you modify the README to text only mode, i.e. the instructions should be in text format only!

2020-08-17 07:37 UTC, Namyalg commented
I assumed adding images will improve the readability. I will make the
necessary changes.

On Mon, Aug 17, 2020, 1:04 PM Pratyay Banerjee <notifications@github.com>
wrote:

> It is highly recommended if you modify the README to text only mode, i.e.
> the instructions should be in text format only!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ankitdobhal/Awesome-Python-Scripts/pull/118#issuecomment-674714860>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM3BEYK65OOI5GPXM67Z6XLSBDMPDANCNFSM4QAZMETA>
> .
>

2020-08-17 07:44 UTC, Namyalg commented
I have made the necessary changes. I would like to know if I have to change anything else

2020-08-17 07:47 UTC, Neilblaze approved these changes
LGTM :+1: 
Good job @Namyalg :tada:

2020-08-18 15:27 UTC, merged