Counter to count the number of items in a list
powerexploit/Awesome-Python-Scripts pull request #119
Opened 2020-08-16 12:12 UTC by Nagasuruthika

Issue #91 
Simple Python Script to count the number of items in a list.

2020-08-16 18:16 UTC, Gaurav451 commented
I would like to work on this issue

2020-08-16 18:23 UTC, Gaurav451 requested changes
In line 5,we can say s=sum(item)

2020-08-17 06:43 UTC, Nagasuruthika commented
@Gaurav451 made few changes in code, do check. **Sum(item) produced a type error**.

2020-08-21 14:07 UTC, SKAUL05 requested changes

2020-08-21 14:07 UTC, SKAUL05 commented on Basic-Scripts/sumofitems_list.py
> +my_list = [1,2,3,4,5,6,7,8,9,10]
Take input from user

2020-08-21 14:36 UTC, SKAUL05 commented
change file name to `sum_of_items_list`

2020-08-21 17:04 UTC, Nagasuruthika commented
@SKAUL05 changes made, do review.

2020-08-21 17:06 UTC, SKAUL05 requested changes
Everything else LGTM:)

2020-08-21 17:06 UTC, SKAUL05 commented on Basic-Scripts/sum_of_items_list.py
> +  n = int(input("Enter number of elements:"))
num instead of n

2020-08-21 17:06 UTC, SKAUL05 commented on Basic-Scripts/sum_of_items_list.py
> +  for i in range(0, n):
index instead of i

2020-08-21 17:11 UTC, Nagasuruthika commented
@SKAUL05 all done :)

2020-08-21 17:12 UTC, SKAUL05 approved these changes
Good to go

2020-08-22 04:30 UTC, merged