Created a program to find the day of the date.
powerexploit/Awesome-Python-Scripts pull request #127
Opened 2020-08-16 17:25 UTC by Mayank662

In this program I calculate the day of the week for any given date of calendar starting from 01/01/2000 to 31/12/2100 without using any inbuilt python function or library.

2020-08-17 06:44 UTC, SKAUL05 requested changes
@Mayank662  Include your algorithm inside a function and call it from main function.
There are too many if else conditions instead of that u can follow switch casing in python which will improve readability of code.
Keep in mind, to follow PEP8 Guidelines closely for naming conventions.
https://www.python.org/dev/peps/pep-0008/

2020-08-20 09:42 UTC, Mayank662 commented
@SKAUL05  Thanks for the review, I have made changes as you have mentioned

2020-08-20 10:52 UTC, SKAUL05 requested changes

2020-08-20 10:52 UTC, SKAUL05 commented on Basic-Scripts/day_of_date.py
> +    t = [
Use suitable and meaningful variable names instead of alphabets.

2020-08-20 10:52 UTC, SKAUL05 commented on Basic-Scripts/day_of_date.py
> +def dayofweek(
Include Docstrings for function definition and follow naming conventions for functions.

2020-09-22 06:51 UTC, closed without merging