I have added script for basic number guessing game.
powerexploit/Awesome-Python-Scripts pull request #131
Opened 2020-08-17 03:12 UTC by richabh456

please review this.

2020-08-17 05:27 UTC, Gaurav451 requested changes
In line 4,we can stop the restriction from 1 to 99 by asking the end point from the user,say it be a.Then line 4 will become randint(1,a).

2020-08-17 05:57 UTC, richabh456 commented
@Gaurav451  Actually here i am asking the user to enter any random number between 1 to 99 only so that the user have to guess number between 1 to 99 only . please suggest if my approach is not right.

2020-08-21 14:41 UTC, SKAUL05 requested changes
@richabh456 
You can ask the user the limit & chances for guessing.
It will make script more dynamic

2020-08-21 17:11 UTC, ultraUnicorn74 reviewed
@SKAUL05 Sir i have made the required changes in code, Please review this.

2020-08-21 17:14 UTC, SKAUL05 requested changes
Everything else LGTM

2020-08-21 17:14 UTC, SKAUL05 commented on Basic-Scripts/guessinggame.py
> +            win = False
No need of this

2020-08-21 17:14 UTC, SKAUL05 commented on Basic-Scripts/guessinggame.py
> +            win = False
No need of this

2020-08-21 17:31 UTC, ultraUnicorn74 commented
@SKAUL05  sir,now is it fine?

2020-08-21 17:36 UTC, SKAUL05 requested changes
Only win = False was required to remove not everything else
U need to print whether number is lower or greater

2020-08-21 17:43 UTC, ultraUnicorn74 commented
@SKAUL05 yes sir got it, Thank you !is it okay now?

2020-08-21 17:49 UTC, SKAUL05 commented on Basic-Scripts/guessinggame.py
> +            win = False
Only remove win= False from this and above else remains same

2020-08-21 17:49 UTC, SKAUL05 commented
> @SKAUL05 yes sir got it, Thank you !is it okay now?

Pls have a look at the comment above

2020-08-22 03:09 UTC, ultraUnicorn74 commented
@SKAUL05 Please review this.

2020-08-22 03:16 UTC, SKAUL05 approved these changes
Good to go :)

2020-08-22 04:32 UTC, merged