Create staicase.py
powerexploit/Awesome-Python-Scripts pull request #136
Opened 2020-08-17 06:55 UTC by Adityanagraj

added a staircase pattern program in python under hakin codes open source contribution

2020-08-17 07:06 UTC, SKAUL05 requested changes
Follow [PEP8 Guidelines ](https://www.python.org/dev/peps/pep-0008/) carefully. 
Document your code. Include main function & using meaningful variable names.

Check File Name spelling.

2020-08-17 07:26 UTC, Adityanagraj commented
I have updated the program with main function and variables @SKAUL05

2020-08-17 08:06 UTC, SKAUL05 requested changes
Change filename to staircase_pattern

2020-08-17 08:06 UTC, SKAUL05 commented on Basic-Scripts/staicase.py
> +   for i in range(1,height+1):
Use meaningful names

2020-08-17 08:06 UTC, SKAUL05 commented on Basic-Scripts/staicase.py
> +def staircase(height):
Add function documentation

2020-08-21 14:23 UTC, SKAUL05 requested changes

2020-08-21 14:23 UTC, SKAUL05 commented on Basic-Scripts/staicase_pattern.py
> +       print(' '*(height-i) + '#'*i)
```suggestion
   for index in range(1,height+1):
       print(' '*(height-index) + '#'*index)
```

2020-08-21 14:23 UTC, SKAUL05 commented on Basic-Scripts/staicase_pattern.py
> +   height=int(input()) #which accepts the input
```suggestion
   height=int(input('Please enter the height of the staircase')) #which accepts the input
```

2020-08-21 14:23 UTC, SKAUL05 commented on Basic-Scripts/staicase_pattern.py
> +   This program prints the staircase pattern for the given height (dynamically)
```suggestion
   This program prints the staircase pattern for the given height (dynamically)
   Params:
       height: height of the staircase as entered by user
   Returns:
       None
```

2020-08-21 14:23 UTC, SKAUL05 commented
Change filename to `staircase_pattern.py`

2020-08-21 15:13 UTC, Adityanagraj commented
what changes i have to do

2020-08-21 17:16 UTC, SKAUL05 commented
> what changes i have to do

Changes suggested above

2020-08-22 13:59 UTC, Adityanagraj commented
I have updated the file from staircase.py to staircase_pattern.py and changed the the code what else i need to do @SKAUL05

2020-08-22 14:34 UTC, SKAUL05 approved these changes
Good to go

2020-08-26 12:25 UTC, Adityanagraj commented
when will the PR gets merged @SKAUL05

2020-08-26 12:26 UTC, SKAUL05 commented
@ankitdobhal Merge pls

2020-08-27 15:54 UTC, merged