Compress the string
powerexploit/Awesome-Python-Scripts pull request #145
Opened 2020-08-17 09:38 UTC by Vaibhavabhaysharma

Through this code I would like  to appreciate the usefulness of the groupby() function of itertools for compressing the string and printing it with its number of occurences.

2020-08-21 14:38 UTC, SKAUL05 requested changes

2020-08-21 14:38 UTC, SKAUL05 commented on Basic-Scripts/Compress_the_string.py
> +S=str(input())                                          # user input for string
```suggestion
uncompressed = str(input("Enter string to compress: "))                                          # user input for string
```

2020-08-21 14:38 UTC, SKAUL05 commented on Basic-Scripts/Compress_the_string.py
> +print(*[(len(list(c)), str(k)) for k, c in groupby(S)]) # logic to print occurence of values in string
```suggestion
print(*[(len(list(value)), str(key)) for key, value in groupby(uncompressed)]) # logic to print occurence of values in string 
```

2020-08-21 14:43 UTC, SKAUL05 requested changes
Change filename to `compress_the_string.py`

2020-08-22 13:23 UTC, Vaibhavabhaysharma reviewed
Resolved requested issue...

2020-08-24 04:45 UTC, SKAUL05 approved these changes

2020-08-24 04:46 UTC, SKAUL05 commented
Good to go @ankitdobhal

2020-08-27 15:51 UTC, merged