Advance Calculator Script in Python #149
powerexploit/Awesome-Python-Scripts pull request #149
Opened 2020-08-17 11:35 UTC by amandp13

#CH20 #149

##Advance Calculator Script 
-Created a script to mimic a calculator using python using a regular expression module.
-It can do all the basic calculations continuously.
-No termination.

2020-08-21 08:46 UTC, SKAUL05 requested changes

2020-08-21 08:46 UTC, SKAUL05 commented on Basic-Scripts/advanceCalculator.py
> +def performMath():
What are u doing specifically in this function?

2020-08-21 08:46 UTC, SKAUL05 commented on Basic-Scripts/advanceCalculator.py
> +        print("You entered:",equn)
Can't see any calculations done!

2020-08-21 10:03 UTC, amandp13 commented on Basic-Scripts/advanceCalculator.py
> +def performMath():
this function is basically allowing users to calculate continuously....as in calculator one can do calculations with multiple variables and multiple operations.

2020-08-21 10:06 UTC, amandp13 commented on Basic-Scripts/advanceCalculator.py
> +        print("You entered:",equn)
Sorry as I committed the wrong basic file as I added the wrong file, now it's okay.
Please review.

2020-08-21 10:50 UTC, SKAUL05 commented
@amandp13 Can u specify Sample I/O in your code and document your function with PEP8 Guidelines.

2020-08-21 16:04 UTC, amandp13 commented
@SKAUL05 Done...please review

2020-08-23 06:20 UTC, amandp13 commented
@ankitdobhal Please review. #149

2020-08-24 04:56 UTC, SKAUL05 approved these changes
Good to go @ankitdobhal

2020-08-25 10:37 UTC, amandp13 commented
@ankitdobhal Please look into this.

2020-08-27 15:49 UTC, merged