Add files via upload
powerexploit/Awesome-Python-Scripts pull request #152
Opened 2020-08-17 16:06 UTC by prasadvpatil

Program to solve the quadratic equation

2020-08-19 11:32 UTC, SKAUL05 requested changes

2020-08-19 11:32 UTC, SKAUL05 commented on Basic-Scripts/quad_equation.py
> +import cmath
Include `main` in your script.
Follow PEP8 Guidelines.
Use docstrings

2020-08-22 05:41 UTC, prasadvpatil commented on Basic-Scripts/quad_equation.py
> +import cmath
@SKAUL05 i have made changes as per your guidance, please review it.
thank you.

2020-08-22 05:47 UTC, SKAUL05 requested changes

2020-08-22 05:47 UTC, SKAUL05 commented on Basic-Scripts/quad_equation.py
> +print(findRoots(a, b, c))
```suggestion
    print(findRoots(a, b, c))

```

2020-08-22 05:58 UTC, prasadvpatil commented on Basic-Scripts/quad_equation.py
> +import cmath
I did the changes now u suggested too. @SKAUL05

2020-08-22 06:00 UTC, SKAUL05 requested changes

2020-08-22 06:00 UTC, SKAUL05 commented on Basic-Scripts/quad_equation.py
> +    print(findRoots(a, b, c))
Wrong indentation

2020-08-22 06:00 UTC, SKAUL05 commented on Basic-Scripts/quad_equation.py
> +    print(findRoots(a, b, c))
Check once properly

2020-08-22 06:57 UTC, SKAUL05 approved these changes
Good to go :)

2020-08-22 07:34 UTC, merged