Adding Python Script For Magic Square
powerexploit/Awesome-Python-Scripts pull request #157
Opened 2020-08-18 06:43 UTC by gulshanbaraik01

Hello,

This is my PR #5 for Awesome Python Scripts. And #3rd one for Basic Scripts. Please review and add it.

Thanks,
Gulshan Baraik

2020-08-19 11:28 UTC, SKAUL05 requested changes

2020-08-19 11:28 UTC, SKAUL05 commented on Basic-Scripts/magic_square1.py
> +def magic_square(n):
Change file_name to magic_square
Include docstrings for function documentation.
Use meaningful variable names

2020-08-19 11:28 UTC, SKAUL05 commented on Basic-Scripts/magic_square1.py
> +    magic_square(3)
Take Input from user
Provide Sample I/O

2020-08-29 14:29 UTC, gulshanbaraik01 commented
Hello, I updated as per your recent suggestions. Please add it, Thanks!!.

2020-09-12 16:50 UTC, SKAUL05 approved these changes
@ankitdobhal Review & Merge

2020-09-24 10:41 UTC, ankitdobhal approved these changes

2020-09-24 10:41 UTC, merged