Sum of primes in the inclusive range of entered number
powerexploit/Awesome-Python-Scripts pull request #163
Opened 2020-08-18 14:08 UTC by Arundhati1Sharma

General python code to find sum of primes upto an entered limit.

2020-08-20 15:38 UTC, SKAUL05 requested changes

2020-08-20 15:38 UTC, SKAUL05 commented on Basic-Scripts/Sum_of_prime.py
> +    return all(a % i for i in range(2, a))
Use meaningful variable names instead of alphabets

2020-08-20 15:38 UTC, SKAUL05 commented on Basic-Scripts/Sum_of_prime.py
> +    main()
Take input from here and call sum_of_primes from here too

2020-08-20 15:38 UTC, SKAUL05 commented on Basic-Scripts/Sum_of_prime.py
> +def sum_of_primes(n):
Document your function using docstrings

2020-08-22 14:12 UTC, Arundhati1Sharma commented
Resolved requested changes.

2020-08-22 14:14 UTC, Arundhati1Sharma reviewed
Resolved requested changes..

2020-08-24 04:48 UTC, SKAUL05 requested changes

2020-08-24 04:48 UTC, SKAUL05 commented on Basic-Scripts/Sum_of_prime.py
> +    return all(is_a_prime % i for i in range(2, is_a_prime))
```suggestion
    return all(is_a_prime % element for element in range(2, is_a_prime))
```

2020-08-24 04:48 UTC, SKAUL05 commented on Basic-Scripts/Sum_of_prime.py
> +    number=int(input())
```suggestion
    number=int(input("Enter value upto which sum of primes to be calculated: "))
```

2020-09-08 12:09 UTC, closed without merging