Image filters using 3-D convolution
powerexploit/Awesome-Python-Scripts pull request #165
Opened 2020-08-18 16:01 UTC by Namyalg

This script can be used to perform 3-D convolution on colored  images. 

Issue related to #93

2020-08-20 06:53 UTC, disha2sinha requested changes

2020-08-20 06:53 UTC, disha2sinha commented on Image-Processing/Image_filters_using_convolution/3D_convolve.py
> +pixels = []
Insert a new line before for loop

2020-08-20 06:53 UTC, disha2sinha commented on Image-Processing/Image_filters_using_convolution/3D_convolve.py
> +      convoluted_matrix = []
Insert new line before for loop

2020-08-20 06:53 UTC, disha2sinha commented on Image-Processing/Image_filters_using_convolution/3D_convolve.py
> +
Remove new lines at the end

2020-08-20 06:53 UTC, disha2sinha commented on Image-Processing/Image_filters_using_convolution/3D_convolve.py
> +            combine[i ,j] = [int(r_convol[i][j]) , int(g_convol[i][j]) , int(b_convol[i][j])]
Remove space before comma and put space after comma

2020-08-20 06:53 UTC, disha2sinha commented on Image-Processing/Image_filters_using_convolution/3D_convolve.py
> +      convoluted_matrix = (np.array(convoluted_matrix).reshape(height-3,width-3))
Put space after comma

2020-08-20 06:53 UTC, disha2sinha commented on Image-Processing/Image_filters_using_convolution/3D_convolve.py
> +            temp = arr[i:i+3 , j:j+3]
Remove space before comma and put space after comma

2020-08-20 06:53 UTC, disha2sinha commented on Image-Processing/Image_filters_using_convolution/3D_convolve.py
> +            prod = np.multiply(temp,kernel)
put space after comma

2020-08-20 06:53 UTC, disha2sinha commented on Image-Processing/Image_filters_using_convolution/3D_convolve.py
> +      for i in range(1,height-2):
Put space after comma

2020-08-20 06:55 UTC, Namyalg commented
I will make the changes right away.

On Thu, Aug 20, 2020, 12:24 PM Disha Sinha <notifications@github.com> wrote:

> *@disha2sinha* requested changes on this pull request.
> ------------------------------
>
> In Image-Processing/Image_filters_using_convolution/3D_convolve.py
> <https://github.com/ankitdobhal/Awesome-Python-Scripts/pull/165#discussion_r473662152>
> :
>
> > +'''b_kernel = np.array([0.11 , 0.11 , 0.11 , 0.11 , 0.11 , 0.11 , 0.11 , 0.11 , 0.11]).reshape(3,3)
> +r_kernel = np.array([0.11 , 0.11 , 0.11 , 0.11 , 0.11 , 0.11 , 0.11 , 0.11 , 0.11]).reshape(3,3)
> +g_kernel = np.array([0.11 , 0.11 , 0.11 , 0.11 , 0.11 , 0.11 , 0.11 , 0.11 , 0.11]).reshape(3,3)
> +'''
> +print("Enter 9 values for each of the streams")
> +b_kernel = np.array(list(map(int, input("Enter the kernel to be applied to the blue stream").split()))).reshape(3,3)
> +r_kernel = np.array(list(map(int, input("Enter the kernel to be applied to the red stream").split()))).reshape(3,3)
> +g_kernel = np.array(list(map(int, input("Enter the kernel to be applied to the green stream").split()))).reshape(3,3)
> +
> +#Image is read and resized
> +
> +img = cv2.imread('path to image')
> +img = cv2.resize(img, (width , height))
> +
> +#The pixels are extracted from the image
> +pixels = []
>
> Insert a new line before for loop
> ------------------------------
>
> In Image-Processing/Image_filters_using_convolution/3D_convolve.py
> <https://github.com/ankitdobhal/Awesome-Python-Scripts/pull/165#discussion_r473662692>
> :
>
> > +              g = []
> +              r = []
> +
> +              for i in pixels:
> +                b.append(i[0])
> +                g.append(i[1])
> +                r.append(i[2])
> +
> +#Each of the streams are resized
> +r = np.array(r).reshape(height, width)
> +b = np.array(b).reshape(height, width)
> +g = np.array(g).reshape(height, width)
> +
> +#function to apply convolution or multiply kernels
> +def convolute(arr , height , width ,kernel):
> +      convoluted_matrix = []
>
> Insert new line before for loop
> ------------------------------
>
> In Image-Processing/Image_filters_using_convolution/3D_convolve.py
> <https://github.com/ankitdobhal/Awesome-Python-Scripts/pull/165#discussion_r473663081>
> :
>
> > +
> +width = width - 3
> +height = height - 3
> +
> +combine = np.zeros([height, width, 3], dtype=np.uint8)
> +
> +for i in range(height):
> +      for j in range(width):
> +            combine[i ,j] = [int(r_convol[i][j]) , int(g_convol[i][j]) , int(b_convol[i][j])]
> +
> +
> +#The 3 matrices or streams are combined, and stored
> +img = Image.fromarray(combine)
> +img.save('Funkyfilter.jpg')
> +
> +
>
> Remove new lines at the end
> ------------------------------
>
> In Image-Processing/Image_filters_using_convolution/3D_convolve.py
> <https://github.com/ankitdobhal/Awesome-Python-Scripts/pull/165#discussion_r473663520>
> :
>
> > +      convoluted_matrix = (np.array(convoluted_matrix).reshape(height-3,width-3))
> +      return(convoluted_matrix)
> +
> +r_convol = convolute(r, height, width, r_kernel)
> +g_convol = convolute(g, height, width, g_kernel)
> +b_convol = convolute(b, height, width, b_kernel)
> +
> +
> +width = width - 3
> +height = height - 3
> +
> +combine = np.zeros([height, width, 3], dtype=np.uint8)
> +
> +for i in range(height):
> +      for j in range(width):
> +            combine[i ,j] = [int(r_convol[i][j]) , int(g_convol[i][j]) , int(b_convol[i][j])]
>
> Remove space before comma and put space after comma
> ------------------------------
>
> In Image-Processing/Image_filters_using_convolution/3D_convolve.py
> <https://github.com/ankitdobhal/Awesome-Python-Scripts/pull/165#discussion_r473663943>
> :
>
> > +
> +#Each of the streams are resized
> +r = np.array(r).reshape(height, width)
> +b = np.array(b).reshape(height, width)
> +g = np.array(g).reshape(height, width)
> +
> +#function to apply convolution or multiply kernels
> +def convolute(arr , height , width ,kernel):
> +      convoluted_matrix = []
> +      for i in range(1,height-2):
> +          for j in range(1,width-2):
> +            temp = arr[i:i+3 , j:j+3]
> +            prod = np.multiply(temp,kernel)
> +            convoluted_matrix.append(np.sum(prod))
> +
> +      convoluted_matrix = (np.array(convoluted_matrix).reshape(height-3,width-3))
>
> Put space after comma
> ------------------------------
>
> In Image-Processing/Image_filters_using_convolution/3D_convolve.py
> <https://github.com/ankitdobhal/Awesome-Python-Scripts/pull/165#discussion_r473664338>
> :
>
> > +              for i in pixels:
> +                b.append(i[0])
> +                g.append(i[1])
> +                r.append(i[2])
> +
> +#Each of the streams are resized
> +r = np.array(r).reshape(height, width)
> +b = np.array(b).reshape(height, width)
> +g = np.array(g).reshape(height, width)
> +
> +#function to apply convolution or multiply kernels
> +def convolute(arr , height , width ,kernel):
> +      convoluted_matrix = []
> +      for i in range(1,height-2):
> +          for j in range(1,width-2):
> +            temp = arr[i:i+3 , j:j+3]
>
> Remove space before comma and put space after comma
> ------------------------------
>
> In Image-Processing/Image_filters_using_convolution/3D_convolve.py
> <https://github.com/ankitdobhal/Awesome-Python-Scripts/pull/165#discussion_r473664564>
> :
>
> > +                b.append(i[0])
> +                g.append(i[1])
> +                r.append(i[2])
> +
> +#Each of the streams are resized
> +r = np.array(r).reshape(height, width)
> +b = np.array(b).reshape(height, width)
> +g = np.array(g).reshape(height, width)
> +
> +#function to apply convolution or multiply kernels
> +def convolute(arr , height , width ,kernel):
> +      convoluted_matrix = []
> +      for i in range(1,height-2):
> +          for j in range(1,width-2):
> +            temp = arr[i:i+3 , j:j+3]
> +            prod = np.multiply(temp,kernel)
>
> put space after comma
> ------------------------------
>
> In Image-Processing/Image_filters_using_convolution/3D_convolve.py
> <https://github.com/ankitdobhal/Awesome-Python-Scripts/pull/165#discussion_r473664795>
> :
>
> > +              r = []
> +
> +              for i in pixels:
> +                b.append(i[0])
> +                g.append(i[1])
> +                r.append(i[2])
> +
> +#Each of the streams are resized
> +r = np.array(r).reshape(height, width)
> +b = np.array(b).reshape(height, width)
> +g = np.array(g).reshape(height, width)
> +
> +#function to apply convolution or multiply kernels
> +def convolute(arr , height , width ,kernel):
> +      convoluted_matrix = []
> +      for i in range(1,height-2):
>
> Put space after comma
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ankitdobhal/Awesome-Python-Scripts/pull/165#pullrequestreview-471291723>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM3BEYKQTSCL7C4VVAR5YQ3SBTCBJANCNFSM4QDWIJUQ>
> .
>

2020-08-22 05:53 UTC, disha2sinha requested changes
Some of the changes requested earlier are yet to be made

2020-08-22 06:00 UTC, disha2sinha requested changes

2020-08-22 06:00 UTC, disha2sinha commented on Image-Processing/Image_filters_using_convolution/3D_convolve.py
> +pixels = []
Make this change

2020-08-22 06:00 UTC, disha2sinha commented on Image-Processing/Image_filters_using_convolution/3D_convolve.py
> +      convoluted_matrix = []
Make this change

2020-08-22 06:00 UTC, disha2sinha commented on Image-Processing/Image_filters_using_convolution/3D_convolve.py
> +            prod = np.multiply(temp,kernel)
Make this change

2020-08-22 06:01 UTC, disha2sinha commented on Image-Processing/Image_filters_using_convolution/3D_convolve.py
> +      convoluted_matrix = (np.array(convoluted_matrix).reshape(height-3,width-3))
Make this change

2020-08-22 06:01 UTC, disha2sinha commented on Image-Processing/Image_filters_using_convolution/3D_convolve.py
> +            combine[i ,j] = [int(r_convol[i][j]) , int(g_convol[i][j]) , int(b_convol[i][j])]
Make this change

2020-08-22 06:02 UTC, disha2sinha commented on Image-Processing/Image_filters_using_convolution/3D_convolve.py
> +
Make changes

2020-08-22 06:19 UTC, Namyalg commented
Yes, I have made them

2020-08-22 06:21 UTC, Namyalg commented
I would want to know if I can submit scripts that I have written using the PyGame module and raise an issue for the same

2020-09-04 16:12 UTC, ankitdobhal commented
> I would want to know if I can submit scripts that I have written using the PyGame module and raise an issue for the same

Great work @Namyalg !
You can submit scripts written using pygame by raising new issue.

2020-09-04 16:40 UTC, Namyalg commented
Okay, will do.

On Fri, Sep 4, 2020, 9:42 PM Ankit Dobhal <notifications@github.com> wrote:

> I would want to know if I can submit scripts that I have written using the
> PyGame module and raise an issue for the same
>
> Great work @Namyalg <https://github.com/Namyalg> !
> You can submit scripts written using pygame by raising new issue.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ankitdobhal/Awesome-Python-Scripts/pull/165#issuecomment-687244840>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM3BEYOORXGU5Y5AHWHCHN3SEEGWNANCNFSM4QDWIJUQ>
> .
>

2020-09-19 17:15 UTC, Namyalg commented
I would like to know if I have to make any changes to these scripts

2020-09-20 04:11 UTC, disha2sinha approved these changes

2020-09-22 06:54 UTC, merged