Twitter Automation Code Added
powerexploit/Awesome-Python-Scripts pull request #168
Opened 2020-08-18 19:49 UTC by sharur7

## Twitter Automation Code

### Pre-requisites:
Must have a Twitter account and Twitter developer account.
Need to add your access keys to use twitter APIs

### Working:
Just run it and it will **like** and **retweet** tweets of the value which you have assigned to the "search".

2020-08-18 21:17 UTC, Neilblaze commented
Amazing work @sharur7 ! :tada: 

Before I approve changes to the PR, I will request you the following changes mentioned below.

- Add README (guide) along with this inside the folder same as your `<filename>`
- Maintain proper [Contribution protocols](https://github.com/ankitdobhal/Awesome-Python-Scripts/blob/master/Contribution.md) (ignore if you're already following it!) & [good practices](https://gist.github.com/sloria/7001839)!

Rest LGTM :+1: 
> + nice & clean code :smile:

2020-08-19 10:01 UTC, sharur7 commented
@Neilblaze Can you please help me my image is not showing up in the README.md file.

2020-08-19 10:35 UTC, Neilblaze commented
> @Neilblaze Can you please help me my image is not showing up in the README.md file.

Change it to this - 
```
<p align="center">
  <img src="twitter image.PNG" width="350px"></p>
```

Sharvari, I'll recommend you a small piece of advice. **Don't** insert any whitespace between any image name. It is considered as a bad practice while working with UTF in markdown.

If the change that I just suggested don't works, just rename the jpg image to twitter.png or image.png & replace the name in the `img` tag!

2020-08-19 11:06 UTC, sharur7 commented
@Neilblaze Thank You! It Worked... Is there any change that I should do more?

2020-08-19 11:26 UTC, Neilblaze requested changes

2020-08-19 11:26 UTC, Neilblaze commented on System-Automation-Scripts/Twitter Automation.py
> +
Delete the two empty lines at the top

2020-08-19 12:30 UTC, sharur7 commented on System-Automation-Scripts/Twitter Automation.py
> +
Yep Done!

2020-08-19 12:30 UTC, sharur7 commented on System-Automation-Scripts/Twitter Automation.py
> +
Should I squash all commits?

2020-08-19 13:03 UTC, Neilblaze commented on System-Automation-Scripts/Twitter Automation.py
> +
Yes, that sounds better! :smiley:

2020-08-19 13:03 UTC, Neilblaze commented on System-Automation-Scripts/Twitter Automation.py
> +
Yep, that sounds better! :smiley:

2020-08-19 16:02 UTC, Neilblaze approved these changes
LGTM!
Awesome work @sharur7 ! :tada:

2020-08-19 19:22 UTC, Neilblaze commented
Code quality looking good :+1: 
@ankitdobhal if possible, resolve the issues please!

2020-08-20 06:57 UTC, merged