Human detection Opencv
powerexploit/Awesome-Python-Scripts pull request #179
Opened 2020-08-19 17:04 UTC by ryuk156

issue : https://github.com/ankitdobhal/Awesome-Python-Scripts/issues/93

About Pull request :
This pr consist of Human detection in an image if a Human is detected in an image the green rectangle will be drawn, it uses pre-trained full-body detect classifier

Demo:

![image](https://user-images.githubusercontent.com/49101492/90429438-5961c880-e0e3-11ea-9e11-fe9364082cef.png)

2020-08-19 17:06 UTC, ryuk156 commented
@ankitdobhal  please review and merge

2020-08-20 07:09 UTC, disha2sinha requested changes
This is not human detection code

2020-08-20 07:13 UTC, ryuk156 commented
ohh ,sry i pushed wrong code ,my bad will change it

2020-08-20 07:21 UTC, ryuk156 commented
@disha2sinha I Have changed the code review, please

2020-08-22 06:05 UTC, disha2sinha requested changes

2020-08-22 06:05 UTC, disha2sinha commented on Image-Processing/Human_detection/Human_detection.py
> +for (x,y,w,h) in cars:  ## the above variable will return 4 cordinates i.e height,width,postionx,positiony
put space after comma

2020-08-22 06:05 UTC, disha2sinha commented on Image-Processing/Human_detection/Human_detection.py
> +img=cv2.imread(img_file) #create image reader
put space around =

2020-08-22 06:05 UTC, disha2sinha commented on Image-Processing/Human_detection/Human_detection.py
> +    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3) ##this loop will create grren rectangle when car is detected
put space after comma

2020-08-22 07:19 UTC, ryuk156 commented
@disha2sinha  done

2020-08-22 07:36 UTC, disha2sinha approved these changes

2020-09-02 15:55 UTC, ankitdobhal commented
> @disha2sinha done

@ryuk156 resolve conflict .

2020-09-03 03:12 UTC, ryuk156 commented
> > @disha2sinha done
> 
> @ryuk156 resolve conflict .

@ankitdobhal this branch multiple conflicts can you explain how i can resolve this

2020-09-30 03:52 UTC, closed without merging