Image crop Open cv
powerexploit/Awesome-Python-Scripts pull request #181
Opened 2020-08-20 06:32 UTC by ryuk156

issue: https://github.com/ankitdobhal/Awesome-Python-Scripts/issues/93

About Pull request :
This pr consist of how we can crop images using Open cv by using this script you can make your own image cropper using different GUI library

Demo:

Before crop:
![image](https://user-images.githubusercontent.com/49101492/90724720-993fd000-e2dc-11ea-87fb-513062ba0dc1.png)

After crop:
![image](https://user-images.githubusercontent.com/49101492/90724756-aceb3680-e2dc-11ea-9760-15a49c3848d7.png)

2020-08-20 06:33 UTC, ryuk156 commented
@ankitdobhal  Review and merge Please

2020-08-20 07:14 UTC, disha2sinha requested changes

2020-08-20 07:14 UTC, disha2sinha commented on Image-Processing/Image_Crop_(resize)/Image_crop.py
> +
Remove new line

2020-08-20 07:14 UTC, disha2sinha commented on Image-Processing/Image_Crop_(resize)/Image_crop.py
> +import cv2 ##import the module
Insert new line

2020-08-20 07:14 UTC, disha2sinha commented on Image-Processing/Image_Crop_(resize)/Image_crop.py
> +
remove new line

2020-08-20 07:14 UTC, disha2sinha commented on Image-Processing/Image_Crop_(resize)/Image_crop.py
> +w=510 ##WIDTH
Give space around =

2020-08-20 15:29 UTC, ryuk156 commented
@ankitdobhal review and merge, please

2020-08-22 06:06 UTC, disha2sinha approved these changes

2020-08-22 07:21 UTC, ryuk156 commented
@ankitdobhal review and merge

2020-08-22 16:33 UTC, merged