Added a pull request template
powerexploit/Awesome-Python-Scripts pull request #184
Opened 2020-08-21 06:00 UTC by AdityaAshvin

A pull request template is added. It contains a Description section, Checklist Section and screenshot section.

Fixes: issue #182

2020-08-21 06:01 UTC, AdityaAshvin commented
Please review it @SKAUL05 .

2020-08-21 06:39 UTC, SKAUL05 requested changes
@ankitdobhal Have a look at this PR for any remaining changes.

2020-08-21 06:39 UTC, SKAUL05 commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> +- [ ] I have added all the reviewers: @ankitdobhal and @SKAUL05
Remove this line not necessary.
Add:
-  I have followed all the appropriate naming conventions.

2020-08-21 07:13 UTC, SKAUL05 requested changes
LGTM 👍 
@ankitdobhal Review and Merge

2020-08-22 05:02 UTC, SKAUL05 commented
Duplicate already issue raised and participant working on it #97

2020-08-22 05:02 UTC, closed without merging