QR scanner Open cv
powerexploit/Awesome-Python-Scripts pull request #188
Opened 2020-08-21 08:31 UTC by ryuk156

issue: https://github.com/ankitdobhal/Awesome-Python-Scripts/issues/93

About Pull request :
This pr consist of how we can scan Barcode using open cv  and pyzbar  to decode your Barcode 

Demo:

Your Qr:
![image](https://user-images.githubusercontent.com/49101492/90869950-931e2200-e3b6-11ea-846d-60548c3fbab3.png)

decoded Text:
![image](https://user-images.githubusercontent.com/49101492/90870034-ab8e3c80-e3b6-11ea-8b15-df3eb7bd7f48.png)

2020-08-21 08:36 UTC, ryuk156 commented
@ankitdobhal  review and merge Please

2020-08-22 06:08 UTC, disha2sinha requested changes

2020-08-22 06:08 UTC, disha2sinha commented on Image-Processing/Qr_scanner/Qr_scanner.py
> +import pyzbar.pyzbar as pyzbar ##import the module pyzbar
Insert a new line

2020-08-22 07:13 UTC, ryuk156 commented
@disha2sinha this imports are already in new line I have inserted a new line after all the imports are done review, please

2020-08-22 07:37 UTC, disha2sinha approved these changes

2020-08-23 06:58 UTC, ryuk156 commented
@ankitdobhal  merge this please

2020-08-29 16:25 UTC, merged