Face detection Open cv
powerexploit/Awesome-Python-Scripts pull request #209
Opened 2020-08-23 14:12 UTC by ryuk156

issue : https://github.com/ankitdobhal/Awesome-Python-Scripts/issues/93

About Pull request :
This pr consist of face detection in an video if a face is detected in an video the green rectangle will be drawn, it uses pre-trained face detect classifier

Demo:

![image](https://user-images.githubusercontent.com/49101492/90980399-b2fd4380-e578-11ea-8105-73f7ef44fcba.png)

2020-08-23 14:15 UTC, ryuk156 commented
@ankitdobhal  please review and merge this pr and  you have merged my car detection pr but that consist of car_detection.py  file but now after you merge that pr somehow file is deleted merge this pr I have included that file in this pr i think when you are making commits the file was deleted

2020-08-28 06:10 UTC, disha2sinha requested changes
Remove car detection from this PR

2020-08-28 06:10 UTC, disha2sinha commented on Image-Processing/Face_detection/Face_detection.py
> +
Remove new line

2020-08-28 06:10 UTC, disha2sinha commented on Image-Processing/Face_detection/Face_detection.py
> +
Remove new line

2020-08-28 06:10 UTC, disha2sinha commented on Image-Processing/Face_detection/Face_detection.py
> +    sucess,img=cap.read()
put space after comma
put space around(after and before) =

2020-08-28 06:10 UTC, disha2sinha commented on Image-Processing/Face_detection/Face_detection.py
> +    faces=face.detectMultiScale(gray,1.1,5)
put space around =
put space after comma

2020-08-28 06:10 UTC, disha2sinha commented on Image-Processing/Face_detection/Face_detection.py
> +        cv2.rectangle(img,( x , y ),( x*w , y*h ),(255,0,0),2)  ##will create the rectangle where face is detected
remove space before comma
put space after comma

2020-08-28 06:10 UTC, disha2sinha commented on Image-Processing/Face_detection/Face_detection.py
> +    if k==27:
remove space before comma
put space after comma
put space around = and ==

2020-09-03 02:43 UTC, ryuk156 commented
@ankitdobhal @disha2sinha   merge this all the changes are done perfectly I have also removed car_detection.py

2020-09-05 15:26 UTC, disha2sinha approved these changes

2020-09-08 12:08 UTC, merged