Added Cartoonify Image Code
powerexploit/Awesome-Python-Scripts pull request #220
Opened 2020-08-28 08:24 UTC by sharur7

### Cartoonifying an image
The code converts your original image i.e. the image which you have given as input, to cartoonified image.
When you run Cartoonify.py, both the input image and output image will be displayed.

### HackinCodes Participant
This PR is associated with the issue:
#93 

@disha2sinha Please review my PR

2020-09-05 15:29 UTC, disha2sinha requested changes

2020-09-05 15:29 UTC, disha2sinha commented on Image-Processing/Cartoonify Image/Cartoonify.py
> +
Remove this new line

2020-09-05 15:29 UTC, disha2sinha commented on Image-Processing/Cartoonify Image/Cartoonify.py
> +
Remove this new line

2020-09-05 15:29 UTC, disha2sinha commented on Image-Processing/Cartoonify Image/Cartoonify.py
> +        cartoon = cv2.bitwise_and(color, color, mask=edges)
give space around =

2020-09-06 14:27 UTC, sharur7 commented on Image-Processing/Cartoonify Image/Cartoonify.py
> +
done

2020-09-06 14:27 UTC, sharur7 commented on Image-Processing/Cartoonify Image/Cartoonify.py
> +
done

2020-09-06 14:27 UTC, sharur7 commented on Image-Processing/Cartoonify Image/Cartoonify.py
> +        cartoon = cv2.bitwise_and(color, color, mask=edges)
done

2020-09-06 14:34 UTC, disha2sinha approved these changes

2020-09-07 18:28 UTC, sharur7 commented
@ankitdobhal Please kindly merge this request

2020-09-08 03:25 UTC, merged