Detecting geometrical shapes using opencv
powerexploit/Awesome-Python-Scripts pull request #247
Opened 2020-09-03 11:56 UTC by simarpreetsingh-019

Detecting geometrical shapes using opencv in python added.

This Pr is in reference to 1st part of #246  being assigned to me in issue #93 label as Medium and CH20. would create readme also in some time.
Please review.

2020-09-05 16:00 UTC, disha2sinha requested changes
Prepare a README.md file with brief description of your work,libraries used and outputs

2020-09-05 16:00 UTC, disha2sinha commented on Image-Processing/Detecting Contours/detecting_geometrical_shapes.py
> +
Remove new line

2020-09-05 16:57 UTC, simarpreetsingh-019 commented on Image-Processing/Detecting Contours/detecting_geometrical_shapes.py
> +
okay, will be updating by morning on all these.

2020-09-06 14:33 UTC, disha2sinha requested changes
Remove issue #246 and link this PR to issue #93

2020-09-06 15:31 UTC, simarpreetsingh-019 commented
@disha2sinha only the ones with admin access can remove or delete that issue 246, so I am not able to do so, maybe you or someone with admin rights can do that.

2020-09-06 15:52 UTC, disha2sinha approved these changes
Yeah by remove I meant close.....my fault

2020-09-06 16:28 UTC, simarpreetsingh-019 commented
ohh , no problem, I have already closed them.
is it ready for merge?

2020-09-17 05:03 UTC, merged