Cropping Images Dynamically
powerexploit/Awesome-Python-Scripts pull request #264
Opened 2020-09-11 08:33 UTC by Pranjalmishra30

Code to crop images by selecting a region of the image. 
Also can save the cropped image. Concepts of MouseEvents are used in this script

Original Issue : https://github.com/ankitdobhal/Awesome-Python-Scripts/issues/93#issuecomment-689375050

2020-09-16 13:21 UTC, Pranjalmishra30 commented
@disha2sinha @ankitdobhal please review my PR.

2020-09-20 04:08 UTC, disha2sinha requested changes
Put space after comma and around operators wherever applicable. Rest all is fine

2020-09-20 04:08 UTC, disha2sinha commented on Image-Processing/ImageCropper/crop.py
> +        refpt = [(x,y)]
Put space after comma

2020-09-20 04:08 UTC, disha2sinha commented on Image-Processing/ImageCropper/crop.py
> +        refpt.append((x,y)) # recording the last coordinates
Put Space after comma

2020-09-20 04:08 UTC, disha2sinha commented on Image-Processing/ImageCropper/crop.py
> +        if len(refpt)==2:
Put space around ==

2020-09-20 04:08 UTC, disha2sinha commented on Image-Processing/ImageCropper/crop.py
> +            roi = clone2[refpt[0][1]:refpt[1][1], refpt[0][0]:refpt[1][0]] # [x1:x2 , y1:y2]
Put space around :

2020-09-20 05:22 UTC, Pranjalmishra30 commented
Updated the file with the suggested changes , please review.

2020-09-24 06:25 UTC, ankitdobhal reviewed
Nice @Pranjalmishra30 .

2020-09-24 06:26 UTC, ankitdobhal approved these changes

2020-09-29 07:51 UTC, merged