added random password generator
powerexploit/Awesome-Python-Scripts pull request #267
Opened 2020-09-13 10:00 UTC by ankitapuri

2020-09-13 13:31 UTC, SKAUL05 requested changes

2020-09-13 13:31 UTC, SKAUL05 commented on Basic-Scripts/random_password.py
> +    for i in range(6):
```suggestion
    for index in range(6):
```

2020-09-13 14:20 UTC, ankitapuri commented
I have the required the change @SKAUL05  sir

2020-09-14 08:57 UTC, SKAUL05 approved these changes
Review & Merge @ankitdobhal

2020-09-24 10:39 UTC, merged