Extract Text from Images Using Python Script
powerexploit/Awesome-Python-Scripts pull request #88
Opened 2020-08-11 07:44 UTC by avinashkranjan

<h4> OCR-Image-to-Text </h4>
<summary> It's a simple script to extract text from any image.  </summary>

Example:
Image Used:

![img](https://user-images.githubusercontent.com/55796944/89870386-63f7fb80-dbd3-11ea-9431-6dc656dc1224.jpg)

Output:

![Screenshot (124)](https://user-images.githubusercontent.com/55796944/89870592-b802e000-dbd3-11ea-8e3a-e81482b94fb4.jpg)

2020-08-16 10:46 UTC, avinashkranjan commented
#93 OCR-Image-to-Text
It's a simple script to extract text from any image.

2020-08-17 14:05 UTC, disha2sinha requested changes

2020-08-17 14:05 UTC, disha2sinha commented on Image-Processing/ocr-img-to-txt.py
> +        r"E:\Python-Programs\PythonProjects\OCR-Image-To-Text\Img-To-Convt\img1.jpg")
bring this in same line with line 10

2020-08-17 14:05 UTC, disha2sinha commented on Image-Processing/ocr-img-to-txt.py
> +
remove this new line

2020-08-17 14:05 UTC, disha2sinha commented on Image-Processing/ocr-img-to-txt.py
> +
remove this new line

2020-08-17 14:18 UTC, disha2sinha commented
Thank you for your contribution @avinashkranjan 
Before I approve changes to the PR, I will request you the following changes mentioned below.

    Add README (guide) along with this inside the folder same as your <filename>
    Update the README with appropriate installation methods and description guidelines.
    Maintain proper Contribution protocols (ignore if you're already following it!) & good practices!

2020-08-18 05:27 UTC, avinashkranjan commented
#155 
@disha2sinha I have made the necessary Changes moved it to a new folder.. Have a look and give the review..
[Here's the Link to New Pull Request](https://github.com/ankitdobhal/Awesome-Python-Scripts/pull/155)

2020-08-18 05:27 UTC, closed without merging